default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: password

development:
  <<: *default
  host: db
  database: help_doctor_development
test:
  <<: *default
  # host: localhost ->CircleCI導入時にこちらへ変更
  host: db
  database: help_doctor_test
production:
  <<: *default
  database: help_doctor_production
  username: help_doctor
  password: <%= ENV['HELP_DOCTOR_DATABASE_PASSWORD'] %>
